### ISSUE TITLE
Investigate: how to address sending broadcast packets over an interface with no ip

### ISSUE THREAD

**Issue by d2g** [d2g/dhcp4client#1]
Currently I've only tested with an interface that already has an IP.

**Comment by ipartner** [comment]
this is indeed needed for this library  to work.

im testing it in a server that already has an ip and dhcpserver

go test -v
=== RUN Test_ExampleClient
--- SKIP: Test_ExampleClient (10.00s)
    client_test.go:34: Success:false
    client_test.go:35: Packet:[]
    client_test.go:39: Test Skipping as it didn't find a DHCP Server
PASS
ok      github.com/d2g/dhcp4client  10.006s

i changed the macaddr to match diferent interfaces in the same server and the result are the same

**Comment by d2g** [comment]
The latest version of the test run against port 1067 & 1068 because codeship (The automatic testing tool) doesn't give root access to allow 67 & 68.

If you update the port numbers in the test from 1067 to 67 and 1068 to 68 you should find it detects a standard DHCP server.

**Comment by ipartner** [comment]
I changed the line 22 Like this

```
c, err := NewInetSock(SetLocalAddr(net.UDPAddr{IP: net.IPv4(0, 0, 0, 0), Port: 68}), SetRemoteAddr(net.UDPAddr{IP: net.IPv4bcast, Port: 67}))
```

Still Fails

[root@host dhcp4client]#go test -v

--- FAIL: Test_ExampleClient (0.00s)
    client_test.go:34: Success:false
    client_test.go:35: Packet:[1 1 6 0 190 157 196 7 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 41 227 209 122 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 99 130 83 99 53 1 1 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
    client_test.go:42: Error:write udp4: network is unreachable
FAIL
exit status 1
FAIL    github.com/d2g/dhcp4client  0.004s
[root@host dhcp4client]#

another detail. how do you set the interface that will listen the responce?

En 14 de mayo de 2015 en 13:33:41, Dan Goldsmith (notifications@github.com) escrito:

The latest version of the test run against port 1067 & 1068 because codeship (The automatic testing tool) doesn't give root access to allow 67 & 68.

If you update the port numbers in the test from 1067 to 67 and 1068 to 68 you should find it detects a standard DHCP server.

**Comment by d2g** [comment]
Yeah, that's how I anticipated it to fail. If I get some time I'll have a look into it. 

If you do find any information (Pull requests welcome also) about how to implement this please post it. At this moment I've no idea of a way forward with this.

**Comment by d2g** [comment]
If you're running a Linux platform I'm not sure if @eyakubovich might be able to assist?

**Comment by ipartner** [comment]
Its a fedora20 virtualized with VmwareFusion 4 network interfaces (all of them with dhcp)

**Comment by eyakubovich** [comment]
Have you tried using pktsock_linux.go? With packet socket, it's possible to do exactly that.
