### ISSUE TITLE
Should be able to provide hostname with request

### ISSUE THREAD

**Issue by onlyjob** [d2g/dhcp4client#22]
Please implement feature to provide _hostname_.

Thanks.

**Comment by d2g** [comment]
The issue is the client does the full request, if you wanted to handle option 12 (http://www.networksorcery.com/enp/protocol/bootp/option012.htm) you'd need to split the request function in it's component parts.

If you've got a simple way of providing me a way to test the functionality (Virtual Machine?) I'll add an additional wrapper that support it out of the box.

**Comment by onlyjob** [comment]
I've used socket-activated _cni-dhcp_ service from [here](https://github.com/containernetworking/plugins/issues/156) with _rkt_ network configuration from [here](https://github.com/rkt/rkt/issues/3945). Starting any container with _rkt_ would then request nameless DHCP address...

**Comment by d2g** [comment]
The v2 branch should now supports this:

`Test_ClientWithOptions` shows how to pass and receive DHCP options.
